# Generated by Django 4.2.11 on 2026-06-21 14:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(help_text='材料批次编号，必须唯一', max_length=50, unique=True, verbose_name='批次编号')),
                ('material_source', models.CharField(help_text='材料的产地或供应商', max_length=200, verbose_name='材料来源')),
                ('diameter', models.FloatField(help_text='材料直径，单位毫米，必须大于0', verbose_name='直径(mm)')),
                ('initial_length', models.FloatField(help_text='材料初始长度，单位毫米，必须大于0', verbose_name='初始长度(mm)')),
                ('description', models.TextField(blank=True, verbose_name='备注说明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '材料批次',
                'verbose_name_plural': '材料批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TensionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tension_force', models.FloatField(help_text='施加的拉力，单位牛顿，必须大于0', verbose_name='拉力值(N)')),
                ('elongation', models.FloatField(help_text='拉伸后的伸长量，单位毫米，不能为负数', verbose_name='伸长量(mm)')),
                ('length_before_rebound', models.FloatField(blank=True, help_text='卸载拉力前的长度，用于计算回弹率', null=True, verbose_name='回弹前长度(mm)')),
                ('length_after_rebound', models.FloatField(blank=True, help_text='卸载拉力恢复后的长度，用于计算回弹率', null=True, verbose_name='回弹后长度(mm)')),
                ('rebound_rate', models.FloatField(blank=True, help_text='自动计算的回弹率', null=True, verbose_name='回弹率(%)')),
                ('is_broken', models.BooleanField(default=False, verbose_name='是否断裂')),
                ('abnormal_break', models.BooleanField(default=False, help_text='是否为异常断裂', verbose_name='异常断裂')),
                ('break_reason', models.TextField(blank=True, help_text='异常断裂时必须填写原因', verbose_name='断裂原因')),
                ('test_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='测试时间')),
                ('notes', models.TextField(blank=True, verbose_name='测试备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tension_tests', to='materials.materialbatch', verbose_name='材料批次')),
            ],
            options={
                'verbose_name': '拉伸测试记录',
                'verbose_name_plural': '拉伸测试记录',
                'ordering': ['-test_time'],
            },
        ),
    ]
