# Generated by Django 4.2.11 on 2026-06-21 16:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialbatch',
            name='broken_at',
            field=models.DateTimeField(blank=True, help_text='样本断裂的时间', null=True, verbose_name='断裂时间'),
        ),
        migrations.AddField(
            model_name='materialbatch',
            name='review_notes',
            field=models.TextField(blank=True, help_text='断裂审核时的备注说明', verbose_name='审核备注'),
        ),
        migrations.AddField(
            model_name='materialbatch',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, help_text='断裂审核完成的时间', null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='materialbatch',
            name='status',
            field=models.CharField(choices=[('active', '正常'), ('testing', '测试中'), ('broken', '已断裂'), ('review', '待审核'), ('archived', '已归档')], default='active', help_text='批次当前流程状态', max_length=20, verbose_name='批次状态'),
        ),
        migrations.AddField(
            model_name='tensiontest',
            name='flag_reason',
            field=models.TextField(blank=True, help_text='数据被标记为异常的原因', verbose_name='异常标记原因'),
        ),
        migrations.AddField(
            model_name='tensiontest',
            name='is_flagged',
            field=models.BooleanField(default=False, help_text='该数据被标记为异常数据', verbose_name='数据异常标记'),
        ),
        migrations.CreateModel(
            name='FatigueTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_force', models.FloatField(help_text='疲劳测试施加的循环载荷，单位牛顿，必须大于0', verbose_name='加载力(N)')),
                ('cycle_count', models.IntegerField(help_text='疲劳测试的循环加载次数，必须大于0', verbose_name='循环次数')),
                ('frequency', models.FloatField(help_text='循环加载频率，单位赫兹，必须大于0', verbose_name='频率(Hz)')),
                ('load_ratio', models.FloatField(blank=True, help_text='最小应力与最大应力之比，通常为-1到1之间', null=True, verbose_name='应力比(R)')),
                ('result', models.CharField(choices=[('intact', '完好'), ('minor_damage', '轻微损伤'), ('major_damage', '严重损伤'), ('broken', '断裂')], default='intact', help_text='疲劳测试后的样本状态', max_length=20, verbose_name='测试结果')),
                ('elongation_after', models.FloatField(blank=True, help_text='疲劳测试完成后的残余伸长量', null=True, verbose_name='测试后伸长量(mm)')),
                ('is_flagged', models.BooleanField(default=False, help_text='该数据被标记为异常数据', verbose_name='数据异常标记')),
                ('flag_reason', models.TextField(blank=True, verbose_name='异常标记原因')),
                ('test_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='测试时间')),
                ('notes', models.TextField(blank=True, verbose_name='测试备注')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatigue_tests', to='materials.materialbatch', verbose_name='材料批次')),
            ],
            options={
                'verbose_name': '疲劳测试记录',
                'verbose_name_plural': '疲劳测试记录',
                'ordering': ['-test_time'],
            },
        ),
        migrations.CreateModel(
            name='DataAnomalyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('tension', '拉伸测试'), ('fatigue', '疲劳测试')], max_length=20, verbose_name='数据来源类型')),
                ('source_id', models.PositiveIntegerField(verbose_name='来源记录ID')),
                ('anomaly_description', models.TextField(help_text='描述检测到的异常情况', verbose_name='异常描述')),
                ('severity', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='严重程度')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('resolution', models.TextField(blank=True, help_text='异常数据处理说明', verbose_name='处理说明')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomaly_logs', to='materials.materialbatch', verbose_name='材料批次')),
            ],
            options={
                'verbose_name': '异常数据日志',
                'verbose_name_plural': '异常数据日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
