# Generated by Django 4.2.11 on 2026-06-22 02:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_materialbatch_broken_at_materialbatch_review_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(verbose_name='快照日期')),
                ('snapshot_type', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月')], default='daily', max_length=20, verbose_name='快照类型')),
                ('total_batches', models.PositiveIntegerField(default=0, verbose_name='总批次数')),
                ('active_batches', models.PositiveIntegerField(default=0, verbose_name='正常批次数')),
                ('broken_batches', models.PositiveIntegerField(default=0, verbose_name='已断裂批次数')),
                ('total_tension_tests', models.PositiveIntegerField(default=0, verbose_name='总拉伸测试数')),
                ('total_fatigue_tests', models.PositiveIntegerField(default=0, verbose_name='总疲劳测试数')),
                ('avg_force', models.FloatField(blank=True, null=True, verbose_name='平均拉力(N)')),
                ('avg_elongation', models.FloatField(blank=True, null=True, verbose_name='平均伸长量(mm)')),
                ('avg_rebound_rate', models.FloatField(blank=True, null=True, verbose_name='平均回弹率(%)')),
                ('anomaly_count', models.PositiveIntegerField(default=0, verbose_name='异常数据数')),
                ('resolved_anomaly_count', models.PositiveIntegerField(default=0, verbose_name='已处理异常数')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '统计快照',
                'verbose_name_plural': '统计快照',
                'ordering': ['-snapshot_date'],
                'unique_together': {('snapshot_date', 'snapshot_type')},
            },
        ),
        migrations.CreateModel(
            name='BreakageFlowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('detected', '断裂检测'), ('review_start', '开始审核'), ('archived', '审核通过-归档'), ('reactivated', '恢复正常'), ('note_added', '添加备注')], max_length=30, verbose_name='流程动作')),
                ('operator', models.CharField(blank=True, max_length=100, verbose_name='操作人')),
                ('notes', models.TextField(blank=True, verbose_name='流程备注')),
                ('source_test_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='关联测试ID')),
                ('source_test_type', models.CharField(blank=True, max_length=20, verbose_name='关联测试类型')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_records', to='materials.materialbatch', verbose_name='材料批次')),
            ],
            options={
                'verbose_name': '断裂流程记录',
                'verbose_name_plural': '断裂流程记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialProcessParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_name', models.CharField(max_length=100, verbose_name='参数名称')),
                ('param_value', models.FloatField(verbose_name='参数值')),
                ('param_unit', models.CharField(blank=True, max_length=20, verbose_name='单位')),
                ('param_type', models.CharField(choices=[('material', '材料属性'), ('process', '工艺参数'), ('environment', '环境条件')], default='material', max_length=20, verbose_name='参数类型')),
                ('description', models.TextField(blank=True, verbose_name='参数说明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='记录时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_params', to='materials.materialbatch', verbose_name='材料批次')),
            ],
            options={
                'verbose_name': '材料工艺参数',
                'verbose_name_plural': '材料工艺参数',
                'ordering': ['param_type', 'param_name'],
                'unique_together': {('batch', 'param_name')},
            },
        ),
    ]
