# Generated by Django 4.2.11 on 2026-06-22 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_statisticalsnapshot_breakageflowrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fatiguetest',
            name='abnormal_break',
            field=models.BooleanField(default=False, help_text='是否为异常断裂', verbose_name='异常断裂'),
        ),
        migrations.AddField(
            model_name='fatiguetest',
            name='break_reason',
            field=models.TextField(blank=True, help_text='异常断裂时必须填写原因', verbose_name='断裂原因'),
        ),
    ]
