# Generated by Django 4.2.11 on 2026-06-22 05:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_fatiguetest_abnormal_break_fatiguetest_break_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='BowType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='弓型名称')),
                ('category', models.CharField(choices=[('traditional', '传统弓'), ('compound', '复合弓'), ('recurve', '反曲弓'), ('longbow', '长弓'), ('crossbow', '弩')], default='traditional', max_length=20, verbose_name='弓型类别')),
                ('min_draw_weight', models.FloatField(help_text='弓的最小拉力要求，单位磅', verbose_name='最小拉力要求(lbs)')),
                ('max_draw_weight', models.FloatField(help_text='弓的最大拉力要求，单位磅', verbose_name='最大拉力要求(lbs)')),
                ('draw_length', models.FloatField(help_text='标准拉距，单位英寸', verbose_name='拉距(英寸)')),
                ('recommended_diameter_min', models.FloatField(help_text='推荐弓弦材料的最小直径', verbose_name='推荐弓弦最小直径(mm)')),
                ('recommended_diameter_max', models.FloatField(help_text='推荐弓弦材料的最大直径', verbose_name='推荐弓弦最大直径(mm)')),
                ('min_tensile_strength', models.FloatField(help_text='弓弦材料的最低抗拉强度要求', verbose_name='最低抗拉强度要求(MPa)')),
                ('min_fatigue_cycles', models.IntegerField(help_text='弓弦材料在标准载荷下的最低循环次数要求', verbose_name='最低疲劳循环次数要求')),
                ('description', models.TextField(blank=True, verbose_name='弓型说明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '弓型配置',
                'verbose_name_plural': '弓型配置',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LifePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('life_score', models.FloatField(help_text='综合耐久性评分，0-100分', verbose_name='寿命评分(0-100)')),
                ('durability_score', models.FloatField(help_text='基于拉伸和疲劳测试的耐久性评分', verbose_name='耐久性评分')),
                ('stability_score', models.FloatField(help_text='基于回弹率和数据一致性的稳定性评分', verbose_name='稳定性评分')),
                ('risk_level', models.CharField(choices=[('low', '低风险'), ('medium', '中风险'), ('high', '高风险'), ('critical', '极高风险')], max_length=20, verbose_name='断裂风险等级')),
                ('risk_score', models.FloatField(help_text='断裂风险指数，越高风险越大', verbose_name='风险指数(0-100)')),
                ('predicted_cycles_to_failure', models.IntegerField(blank=True, null=True, verbose_name='预测断裂循环次数')),
                ('predicted_lifetime_hours', models.FloatField(blank=True, null=True, verbose_name='预计使用寿命(小时)')),
                ('key_factors', models.JSONField(default=list, verbose_name='关键影响因素')),
                ('warning_signs', models.JSONField(default=list, verbose_name='预警信号')),
                ('recommendations', models.TextField(blank=True, verbose_name='优化建议')),
                ('predicted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='预测时间')),
                ('is_latest', models.BooleanField(default=True, verbose_name='是否为最新预测')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_predictions', to='materials.materialbatch', verbose_name='材料批次')),
            ],
            options={
                'verbose_name': '寿命预测记录',
                'verbose_name_plural': '寿命预测记录',
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(help_text='材料属性相似度评分', verbose_name='相似度评分(0-100)')),
                ('performance_score', models.FloatField(help_text='推荐材料相对于源材料的性能提升', verbose_name='性能提升评分')),
                ('overall_score', models.FloatField(help_text='综合相似度和性能提升的推荐评分', verbose_name='综合推荐评分')),
                ('similarity_factors', models.JSONField(default=dict, verbose_name='相似度因素详情')),
                ('advantages', models.JSONField(default=list, verbose_name='推荐优势')),
                ('caveats', models.JSONField(default=list, verbose_name='注意事项')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='推荐时间')),
                ('recommended_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_to', to='materials.materialbatch', verbose_name='推荐材料批次')),
                ('source_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_from', to='materials.materialbatch', verbose_name='源材料批次')),
            ],
            options={
                'verbose_name': '材料推荐记录',
                'verbose_name_plural': '材料推荐记录',
                'ordering': ['-overall_score'],
                'unique_together': {('source_batch', 'recommended_batch')},
            },
        ),
        migrations.CreateModel(
            name='BowTypeMatching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_level', models.CharField(choices=[('excellent', '极佳匹配'), ('good', '良好匹配'), ('fair', '一般匹配'), ('poor', '不推荐')], max_length=20, verbose_name='匹配等级')),
                ('match_score', models.FloatField(help_text='材料与弓型的综合匹配度', verbose_name='匹配度评分(0-100)')),
                ('criteria_results', models.JSONField(default=dict, verbose_name='各项匹配标准结果')),
                ('notes', models.TextField(blank=True, verbose_name='匹配说明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='匹配时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bow_type_matchings', to='materials.materialbatch', verbose_name='材料批次')),
                ('bow_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_matchings', to='materials.bowtype', verbose_name='弓型')),
            ],
            options={
                'verbose_name': '弓型匹配记录',
                'verbose_name_plural': '弓型匹配记录',
                'ordering': ['-match_score'],
                'unique_together': {('batch', 'bow_type')},
            },
        ),
        migrations.CreateModel(
            name='BatchRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_type', models.CharField(choices=[('lifetime', '寿命排行'), ('durability', '耐久性排行'), ('stability', '稳定性排行'), ('performance', '性能排行'), ('overall', '综合排行')], max_length=20, verbose_name='排行类型')),
                ('rank', models.IntegerField(verbose_name='排名')),
                ('score', models.FloatField(verbose_name='排行评分')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='排行时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='materials.materialbatch', verbose_name='材料批次')),
            ],
            options={
                'verbose_name': '批次排行记录',
                'verbose_name_plural': '批次排行记录',
                'ordering': ['ranking_type', 'rank'],
                'unique_together': {('ranking_type', 'batch')},
            },
        ),
    ]
