from django.urls import path
from . import views

app_name = 'materials'

urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('batches/', views.MaterialBatchListView.as_view(), name='batch_list'),
    path('batches/<int:pk>/', views.MaterialBatchDetailView.as_view(), name='batch_detail'),
    path('batches/create/', views.MaterialBatchCreateView.as_view(), name='batch_create'),
    path('batches/<int:pk>/edit/', views.MaterialBatchUpdateView.as_view(), name='batch_edit'),
    path('batches/<int:pk>/delete/', views.MaterialBatchDeleteView.as_view(), name='batch_delete'),
    path('batches/<int:pk>/review/', views.BatchReviewView.as_view(), name='batch_review'),
    path('batches/<int:pk>/flow-note/', views.BatchFlowNoteView.as_view(), name='batch_flow_note'),
    path('batches/<int:batch_pk>/tests/add/', views.TensionTestCreateView.as_view(), name='test_create'),
    path('tests/<int:pk>/edit/', views.TensionTestUpdateView.as_view(), name='test_edit'),
    path('tests/<int:pk>/delete/', views.TensionTestDeleteView.as_view(), name='test_delete'),
    path('batches/<int:batch_pk>/fatigue/add/', views.FatigueTestCreateView.as_view(), name='fatigue_test_create'),
    path('fatigue/<int:pk>/edit/', views.FatigueTestUpdateView.as_view(), name='fatigue_test_edit'),
    path('fatigue/<int:pk>/delete/', views.FatigueTestDeleteView.as_view(), name='fatigue_test_delete'),
    path('batches/<int:batch_pk>/params/add/', views.ProcessParamCreateView.as_view(), name='param_create'),
    path('params/<int:pk>/edit/', views.ProcessParamUpdateView.as_view(), name='param_edit'),
    path('params/<int:pk>/delete/', views.ProcessParamDeleteView.as_view(), name='param_delete'),
    path('compare/', views.BatchCompareView.as_view(), name='batch_compare'),
    path('statistics/', views.StatisticsView.as_view(), name='statistics'),
    path('anomalies/', views.AnomalyListView.as_view(), name='anomaly_list'),
    path('anomalies/<int:pk>/resolve/', views.AnomalyResolveView.as_view(), name='anomaly_resolve'),
    path('life-prediction/', views.LifePredictionDashboardView.as_view(), name='life_prediction_dashboard'),
    path('batches/<int:pk>/run-prediction/', views.RunLifePredictionView.as_view(), name='run_life_prediction'),
    path('run-all-predictions/', views.RunAllLifePredictionsView.as_view(), name='run_all_predictions'),
    path('life-prediction/<int:pk>/', views.LifePredictionDetailView.as_view(), name='life_prediction_detail'),
    path('batches/<int:pk>/recommendations/', views.BatchRecommendationsView.as_view(), name='batch_recommendations'),
    path('batches/<int:pk>/bow-matching/', views.BatchBowMatchingView.as_view(), name='batch_bow_matching'),
    path('rankings/', views.BatchRankingView.as_view(), name='batch_ranking'),
    path('run-rankings/', views.RunBatchRankingsView.as_view(), name='run_batch_rankings'),
    path('api/batch-stats/<int:pk>/', views.BatchStatsAPIView.as_view(), name='api_batch_stats'),
    path('api/global-stats/', views.GlobalStatsAPIView.as_view(), name='api_global_stats'),
    path('api/calc-rebound/', views.CalculateReboundAPIView.as_view(), name='api_calc_rebound'),
    path('api/life-prediction/<int:pk>/', views.ApiLifePredictionView.as_view(), name='api_life_prediction'),
    path('api/batch-recommendations/<int:pk>/', views.ApiBatchRecommendationsView.as_view(), name='api_batch_recommendations'),
    path('api/bow-matching/<int:pk>/', views.ApiBowMatchingView.as_view(), name='api_bow_matching'),
    path('api/batch-ranking/', views.ApiBatchRankingView.as_view(), name='api_batch_ranking'),
    path('api/prediction-viz/<int:pk>/', views.ApiPredictionVisualizationView.as_view(), name='api_prediction_viz'),

    path('recipes/', views.RecipeListView.as_view(), name='recipe_list'),
    path('recipes/<int:pk>/', views.RecipeDetailView.as_view(), name='recipe_detail'),
    path('recipes/create/', views.RecipeCreateView.as_view(), name='recipe_create'),
    path('recipes/<int:pk>/edit/', views.RecipeUpdateView.as_view(), name='recipe_edit'),
    path('recipes/<int:pk>/delete/', views.RecipeDeleteView.as_view(), name='recipe_delete'),
    path('recipes/<int:pk>/predict/', views.RunRecipePredictionView.as_view(), name='run_recipe_prediction'),
    path('recipes/<int:pk>/suggestions/', views.RecipeSuggestionsView.as_view(), name='recipe_suggestions'),
    path('recipes/<int:pk>/viz/', views.ApiRecipeVisualizationView.as_view(), name='api_recipe_viz'),

    path('trials/', views.TrialPlanListView.as_view(), name='trial_list'),
    path('trials/<int:pk>/', views.TrialPlanDetailView.as_view(), name='trial_detail'),
    path('trials/create/', views.TrialPlanCreateView.as_view(), name='trial_create'),
    path('trials/<int:pk>/edit/', views.TrialPlanUpdateView.as_view(), name='trial_edit'),
    path('trials/<int:pk>/start/', views.TrialPlanStartView.as_view(), name='trial_start'),
    path('trials/<int:pk>/complete/', views.TrialPlanCompleteView.as_view(), name='trial_complete'),
    path('trials/<int:pk>/results/add/', views.TrialResultCreateView.as_view(), name='trial_result_create'),
    path('trial-results/<int:pk>/edit/', views.TrialResultUpdateView.as_view(), name='trial_result_edit'),
    path('trial-results/<int:pk>/evaluate/', views.EvaluateTrialResultView.as_view(), name='trial_result_evaluate'),
    path('trials/<int:pk>/analyze/', views.TrialAnalysisView.as_view(), name='trial_analysis'),

    path('recipe-compare/', views.RecipeCompareView.as_view(), name='recipe_compare'),

    path('api/recipe/<int:pk>/prediction/', views.ApiRecipePredictionView.as_view(), name='api_recipe_prediction'),
    path('api/recipe-compare/', views.ApiRecipeCompareView.as_view(), name='api_recipe_compare'),
    path('api/trial-analysis/<int:pk>/', views.ApiTrialAnalysisView.as_view(), name='api_trial_analysis'),
    path('api/recipe-suggestions/<int:pk>/', views.ApiRecipeSuggestionsView.as_view(), name='api_recipe_suggestions'),
]
